### ISSUE TITLE
Can a Search be added ?

### ISSUE THREAD

**Issue by drogga** [MuntashirAkon/SetEdit#3] opened 2020-11-22 23:50 UTC
Hi, can somehow a Search be build-in \ added (it's super hard to find something particular in it) ?, cuz the Dev said that it will no longer be updated with fixes or any improvements (because of Google)...

**Comment by drogga** [comment] 2020-11-23 00:18
^ @MuntashirAkon ^

**Comment by MuntashirAkon** [comment] 2020-11-23 00:29
Alright.

**Comment by MuntashirAkon** [comment] 2020-11-23 03:35
Fixed via 72cbea1

**Closed by MuntashirAkon** 2020-11-23 03:35 UTC

**Comment by drogga** [comment] 2020-11-23 11:27
"For the first 3 tables, searching only matches the whole key due to an inherent limitation." - that sux, can it ever be fixed\improved ?

"Day/night theme for supported devices" - unfortunately here on SGN 10.1 Android 4.1.2 device it is completely white and there's no way to change\switch to dark (it's very ugly that way - it was perfect for me before, because it used "Device's Default theme, which here on Samsung TouchWiz looked awesome with native black ui)...!

The .apk file size has grown a low (mainly because of classes.dex), does it contain a "debug" code in it, or only adding the search support made it so "fat" ?

Can I Please get a mod with nothing else changed, but added the search function (I don't kno if it will even be possible now, because you updated the whole git\repo and go with AndroidX...) ?

Thanks in advance ;)

**Comment by MuntashirAkon** [comment] 2020-11-23 15:07
There are too many report in a single and unrelated issue. But I'll address them anyway:

> "For the first 3 tables, searching only matches the whole key due to an inherent limitation." - that sux, can it ever be fixed\improved ?

It can be fixed. But it will take some time to find a feasible way. (I can't study things like that now as I'm really very busy with other things.)

> "Day/night theme for supported devices" - unfortunately here on SGN 10.1 Android 4.1.2 device it is completely white and there's no way to change\switch to dark (it's very ugly that way - it was perfect for me before, because it used "Device's Default theme, which here on Samsung TouchWiz looked awesome with native black ui)...!

Sorry, I haven't realised that anybody's still using a pre-lollipop OS. I'll probably add some preferences or something like that.

> The .apk file size has grown a low (mainly because of classes.dex), does it contain a "debug" code in it, or only adding the search support made it so "fat" ?

This is because of the migration to AndroidX. It's really difficult to support API 14 to API 29 without using the compatibility library. This size will only grow as new features are added. But since you asked, I'll try to minimise the binary as much as possible using obfuscation technique.

> Can I Please get a mod with nothing else changed, but added the search function (I don't kno if it will even be possible now, because you updated the whole git\repo and go with AndroidX...) ?

If you insist, I can provide you a build without the migration. But you have to understand that I cannot continue that in future. I'm sorry if you're disappointed but the problem is the change between each Android release is too much and we, the devs, have really hard time working on compatibility issues.

**Comment by drogga** [comment] 2020-11-23 23:05
To be honest, I think that GirHub is a bit too basic (stupid) as of communication between users functionality\ability and features is close to none, I mean you don't have a simple PMs functionality, chat or anything like that and when the repo owner, contributor(s) or whatever don't provide a e-mail address or any form of contact details, your only choice is to write\open a "issue", which can't even be deleted by it's author, so I prefer writing everything on one place (in one single issue), instead of opening like 4 (in this case) or more. I think that all the four points are related and huge thanks for addressing them anyway, even tho you don't think the same... ;)

As soon as you can fix the search = better, I will wait...

If you ask me, if the search could've been also added and nothing else had to be changed\updated it would've been better that way (which I much prefer) over now, because I've never had any issues with this app (the PlayStore original version) on Androids from 4 to 10, also it was with a native dark theme by default everywhere I install it, never white, so adding themes support was superfluous\pointless\meaningless according to me...
Yes please, I would really like to have it as it was - with nothing but fully functional Search, but until you figure a workaround\fix for that, there's basically no point in build-ing \ compiling a .apk with only partially working Search.

**Comment by MuntashirAkon** [comment] 2020-11-24 02:35
> If you ask me, if the search could've been also added and nothing else had to be changed\updated it would've been better that way (which I much prefer) over now, because I've never had any issues with this app (the PlayStore original version) on Androids from 4 to 10

This isn't the SetEdit made by **4A** available at Google Play Store (which was never made open source). There isn't any connection between the two other than the fact that both have the same name (the original SetEdit has a different app label though) and have the same design.

> so adding themes support was superfluous\pointless\meaningless according to me...

I haven't added any theme. This is the default option in AndroidX.

**Comment by drogga** [comment] 2020-11-24 08:50
I hope you are not trying to convince me that this is made\build from scratch\the ground up, has absolutely nothing to do with the same app by @4A and it's not just a decompiled\decoded to java modded fork of his, then why did you credited him in the app's description here (readme.md).., because your first build (v1.0) looks exactly like his, with a few minor differences, like without the feature pack (!) and the "font" buttons at the top right corner and only better looking and wider string lines, 
anyway, the 4A's one works on 3.0+ (api\sdk 11) and uses a Holo Dark theme on older than 5.0 LP (before the "material design" ever existed) and your first version build used the device default\native theme (=both apps are\were with Black or Dark grey\gray everywhere) and looked the same on 5.0+ LP, but unfortunately your v1.1 (latest build) is with\in ugly ass White on 4.1.2 JB and 7.0 Nougat, so - sorry but I can't \ don't accept and like that UI.
So, as I basically already said - I would like it as it was in v1.0, plus a properly working Search (bar\button) and nothing else "touched"...

**Comment by drogga** [comment] 2020-11-24 09:14
{ Damn you "AndroidX", it turns out that all the fault is yours, you fu*k up everything - I hate you :D }

**Comment by drogga** [comment] 2021-04-06 14:15
@MuntashirAkon I'm still looking forward for\to a Dark Theme when there's no System toggle (for lower than A.9 Pie - SDK\API 28), for example you can get rid of the white UI completely, because I'm sure nobody likes it anyways, or tune the "styles.xml" in "values" \ "values-night" a bit - to "values-v28" and use "DeviceDefault" (14>21<) or "Material" (21>28>) for everything lower than 9 Pie.

BTW - I probably already mentioned it, but the search is barely usable, it needs a lot of work....

**Comment by MuntashirAkon** [comment] 2021-04-06 16:27
> I probably already mentioned it, but the search is barely usable, it needs a lot of work

Search in the first three tabs are not usable as they return only the matched values. An alternative way would be to cache all the key names so that they can be matched with the search term.

**Comment by drogga** [comment] 2021-04-07 07:06
Yes, whatever it takes, as long as it works... :+1:
I hope that you finally have some spare time to work on the theme too. ;)

**Comment by MuntashirAkon** [comment] 2021-06-06 04:19
Implemented in ce681e0

**Comment by drogga** [comment] 2021-06-07 07:39
Thanks.
Dialog(s) borders are not visible with dark theme, maybe you can tune their color a bit ;
Basically there's no point of the value edit dialog to appear in \ on the non-editable 3 tables ;
State is not resumed when you rotate, it doesn't remember where you exactly where and what you were doing before the screen rotation, instead it resets it's state, IDK, but maybe you should add back the [android:resumeWhilePausing="true"] ;
In landscape orientation the keyboard dialog is in full screen on\on Search and Edit, IDK, but maybe you should probably add back [android:configChanges="keyboardHidden"] in the manifest, separating the 2 with activities or something like that ;

I have no idea what's the purpose \ point of this, since you don't seem to be using [android:resizeableActivity], anyway - TLDR:
```
<meta-data
            android:name="android.max_aspect"
            android:value="2.4" />
```

Please replace back disroot.org's searx instance with Google _(since v1.2)_, because not everyone wants \ prefers to use it _(personally I can't and don't want to use that)_. Thanks.

_Those are just personal observations \ opinions with some suggestions (maybe with a bit of constructive criticism), so you don't have to feel obligated to take them into account !_

**Comment by MuntashirAkon** [comment] 2021-06-07 07:56
Although most of the opinions have no relation with the **search** issue, I'll address them anyway considering your past history.

> Dialog(s) borders are not visible with dark theme, maybe you can tune their color a bit ;

This is intended. You should probably brighten your screen at this point.

> Basically there's no point of the value edit dialog to appear in \ on the non-editable 3 tables ;

Yes, there is. Because it's not an edit dialog on the other lists. You can only copy them, you cannot edit them (as you've probably seen that there's no save or delete button). The UI is kept similar in order to avoid inconsistency and to give the user a message that the tables aren't editable.

> State is not resumed when you rotate, it doesn't remember where you exactly where and what you were doing before the screen rotation, instead it resets it's state, IDK, but maybe you should add back the [android:resumeWhilePausing="true"] ;

That won't fix it. I need to add back `configChanges` but that has other problems when a custom theme is involved. Considering it as a very low priority issue, I may work it out in a future version.

> I have no idea what's the purpose \ point of this, since you don't seem to be using [android:resizeableActivity]

To enable support for gesture navigation on Android 10 or later as stated in the changlog.

> Please replace back disroot.org's searx instance with Google _(since v1.2)_, because not everyone wants \ prefers to use it _(personally, I can't and don't want to use that, even if I could)_. Thanks in advance.

Unfortunately, we, the F-Droid contributors, don't like or promote any app which mines our or our users' data.

**Comment by drogga** [comment] 2021-06-07 08:38
Not a solution, but it's the same even at max brightness, a brighter grey color can easily be used for\on them instead...

Yes, I noticed, but then the dialog should be at least read-only in this case, but then the message for 'not editable' won't appear that way at all, because currently it only does show after I purposely try to edit them anyway, so it expects me to do that in order to tell \ notify me...

It's not about a "app", I didn't mentioned any, it's about a search engine _(SetEdit asks me to open a browse in order to perform a web online search with the key name when I click on the "(?)" icon button)_, also everything collects ("mines") data, especially nowadays and anonymity and privacy are just a myth \ illusion.

BTW - I edited my comment, adding 2 more I forgot, before I could see that you replied.

What about the FullScreen keyboard input window ?

Thanks for replying and the info anyway, have a nice day/night and I wish you all the best ;-)

**Comment by MuntashirAkon** [comment] 2021-06-07 08:57
> Not a solution, but it's the same even at max brightness, a brighter grey color can easily be used for\on them instead...

The background colour the dialogs use is brighter than the activity. It's probably an issue with your device screen.

> Yes, I noticed, but then the dialog should be at least read-only in this case, but then the message for 'not editable' won't appear that way at all, because currently it only does show after I purposely try to edit them anyway, so it expects me to do that in order to tell \ notify me...

They _are_ read-only in the other three tables. If it's editable on your device, it could be due to some other issue.

> It's not about a "app", I didn't mentioned any, it's about a search engine _(SetEdit asks me to open a browse in order to perform a web online search with the key name when I click on the "(?)" icon button)_,

FYI, Google search is a web "app".

> also everything collects ("mines") data, especially nowadays and anonymity and privacy are just a myth \ illusion.

Not to us who are aware of them and promote them. You should've done some research before claiming something.

> What about the FullScreen keyboard input window ?

What about it?

**Comment by drogga** [comment] 2021-06-07 09:38
Barely...
Do you want a screenshot ?
_App tested on Samsung A6+ with Android 10 (One UI 2.0) with Auto-Brightness & Adaptive Screen color profile._

I already corrected myself before that, check the last edit, you quoted my old text, sorry, apologies for that.

Also added more details on that part.
I don't exactly know what's your understanding on that and what do you mean...
_If a search engine doesn't load even in IE on XP, I simply can't rely on it._
_I've done enough research throughout the years to know, I'm over 30_.

Nothing, just if it can NOT be like that - taking up the whole screen, not allowing you to see the app and content while typing.

**Comment by drogga** [comment] 2021-06-10 08:09
^Screenshot attached^

**Comment by drogga** [comment] 2021-06-10 08:16
^Screenshot attached^
Also as you can see there's a tiny issue in this dialog - nothing is selected, but it should be the one that is currently using, which is "Follow system" in my case, but this isn't important.

I don't think that there's a need to attach one for the fullscreen KB/IME...
